#!/bin/sh

#
# Gradle start up script for POSIX generated by the Gradle wrapper plugin.
# NOTA DEL EQUIPO ECOCICLOS: este proyecto no incluye gradle-wrapper.jar
# porque el entorno de generación no tenía acceso a services.gradle.org.
# El workflow de GitHub Actions (.github/workflows/android.yml) ejecuta
# `gradle wrapper --gradle-version 8.7` como primer paso para regenerar
# ese binario automáticamente antes de compilar. Ver docs/BUILD_REPORT.md.
#

PRG="$0"
APP_HOME=$(cd "$(dirname "$PRG")" && pwd -P) || exit 1

APP_NAME="Gradle"
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

MAX_FD="maximum"

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

CLASSPATH="\$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
    die "ERROR: gradle-wrapper.jar no encontrado. Ejecuta 'gradle wrapper --gradle-version 8.7' una vez (con Gradle instalado o vía CI) antes de usar ./gradlew localmente."
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_NAME" \
    -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
    org.gradle.wrapper.GradleWrapperMain "$@"
